GET http://localhost:8083/templates

POST http://localhost:8083/templates/purple
Content-Type: application/json

{
    "title": "Картельные сговоры не допускают ситуации, при которой базовые сценарии поведения пользователей формируют глобальную",
    "message": "Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня представляет собой интересный эксперимент проверки поэтапного и последовательного развития общества. Картельные сговоры не допускают ситуации, при которой диаграммы связей освещают чрезвычайно интересные особенности картины в целом, однако конкретные выводы, разумеется, функционально разнесены на независимые элементы. Разнообразный и богатый опыт говорит нам, что перспективное планирование обеспечивает широкому кругу (специалистов) участие в формировании как самодостаточных, так и внешне зависимых концептуальных решений."
}


GET http://195.123.212.76:8083/templates


POST http://195.123.212.76:8083/templates/purple
Content-Type: application/json

{
    "title": "this is title",
    "message": "this is message"
}


