GET http://localhost:8083/templates

POST http://localhost:8083/templates/purple
Content-Type: application/json

{
    "title": "Картельные сговоры не допускают ситуации, при которой базовые сценарии поведения пользователей формируют глобальную",
    "message": "Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня представляет собой интересный эксперимент проверки поэтапного и последовательного развития общества. Картельные сговоры не допускают ситуации, при которой диаграммы связей освещают чрезвычайно интересные особенности картины в целом, однако конкретные выводы, разумеется, функционально разнесены на независимые элементы. Разнообразный и богатый опыт говорит нам, что перспективное планирование обеспечивает широкому кругу (специалистов) участие в формировании как самодостаточных, так и внешне зависимых концептуальных решений."
}


GET http://195.123.212.76:8083/templates


POST http://195.123.212.76:8083/templates/red
Content-Type: application/json

{
    "title": "При создании генератора мы использовали небезизвестный универсальный код речей. Текст генерируется абзацами случайным образом",
    "message": "Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение нашей деятельности играет важную роль в формировании существенных финансовых и административных условий. Товарищи! сложившаяся структура организации требуют определения и уточнения системы обучения кадров, соответствует насущным потребностям. С другой стороны дальнейшее развитие различных форм деятельности в значительной степени обуславливает создание позиций, занимаемых участниками в отношении поставленных задач."
}


